    all:
      hosts:
        remote:
          ansible_connection: ssh
          ansible_user: st # Remote user
          ansible_ssh_pass : st
          ansible_ssh_private_key_file : /home/st/.ssh/id_rsa
          ansible_sudo_pass : st  
          ansible_host: 10.10.0.52 # Remote host
          ansible_port: 22